name: default
on:
  - push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry
          key: ${{ runner.os }}-yarn
      - name: Install dependencies
        run: |
          corepack enable
          yarn set version latest
          yarn install --immutable
      - name: Run
        run: yarn run test
        continue-on-error: true
      - name: Run (experimental resolver)
        run: yarn run test-with-experimental-resolver
        continue-on-error: true
      - name: Run (custom resolver)
        run: yarn run test-with-custom-resolver
      - name: 'Run (nodeLinker: node-modules)'
        run: |
          yarn config set nodeLinker node-modules
          yarn install --immutable
          yarn run test-with-node-modules
